version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: react-docker:profrontend
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'run', 'test']
